### ISSUE TITLE
To-Do's for Problem Statement / Dev Plan Deliverables

### ISSUE THREAD

**Issue by nguyes44** [nguyes44/McMasterTransit#7]
**Stalled for Monday**:
- [x] Revise the design thinking section of "extras" in Problem Statement deliverable after Monday Sept 23rd's tutorial discussion
- [x] Ask about input/output and environment in the Problem Statement deliverable on Monday

**Dev Plan To Do**:
- [x] Organize action items into individual issues
- [x] We are going to split the goals and explain two things: why is the goal there in the first place, and how are these goals measurable?
- [x] Change the project name to not awesome bus
- [x] 4 (team meeting plans)
- [x] 6 (what could be new roles?),
- [x] 8 (needs to be flushed out, require a high level schedule on when things were due and a buffer date before actual date),
- [x] 9 (write out large paragraphs, consequences of a bad PoC),
- [x] 7 (describe all labels),
- [x] 10,
- [x] 11 (look into if any additional coding best practices are necessary)

**Problem Statement To Do:**
- [x] Environment section
- [x] Refine alternate input/output section

**Individual**:
- [x] import your Google Doc section into TeX
- [x] individual dev plan reflection

**Comment by george536** [comment]
Change the project name to not awesome bus: MacTransit Task Board

**Comment by nguyes44** [comment]
Done: Added reason and how to measure to each goal / stretch goal
